version: '3.7'
services:
  backend:
    build: ./packages/backend
    ports:
      - "5000:5000"
    env_file:
      - ./packages/backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./packages/frontend/.env
