services:
  Coins.coins.application.CoinGeckoService:
    class: ../../../../../Contexts/CoinsCtx/Coins/infrastructure/AxiosCoinGeckoService
    arguments: ['']

  Coins.coins.application.CoinsGetAll:
    class: ../../../../../Contexts/CoinsCtx/Coins/application/CoinsGetAll
    arguments: ['@Coins.coins.application.CoinGeckoService']

  Coins.coins.application.CoinsGetTrending:
    class: ../../../../../Contexts/CoinsCtx/Coins/application/CoinsGetTrending
    arguments: ['@Coins.coins.application.CoinGeckoService']

  Coins.auth.domain.UserRepository:
    class: ../../../../../Contexts/CoinsCtx/Auth/infrastructure/SanityUserRepository
    arguments: ['']

  Coins.auth.application.UserRegister:
    class: ../../../../../Contexts/CoinsCtx/Auth/application/UserRegister
    arguments: ['@Coins.auth.domain.UserRepository']

  Coins.auth.application.UserLogin:
    class: ../../../../../Contexts/CoinsCtx/Auth/application/UserLogin
    arguments: ['@Coins.auth.domain.UserRepository']
