services:
  Coins.coins.application.CoinGeckoService:
    class: ../../../../../Contexts/CoinsCtx/Coins/infrastructure/AxiosCoinGeckoService
    arguments: [ '' ]

  Coins.coins.application.CoinsGetAll:
    class: ../../../../../Contexts/CoinsCtx/Coins/application/CoinsGetAll
    arguments: [ '@Coins.coins.application.CoinGeckoService' ]

  Coins.coins.application.CoinsGetTrending:
    class: ../../../../../Contexts/CoinsCtx/Coins/application/CoinsGetTrending
    arguments: [ '@Coins.coins.application.CoinGeckoService' ]

  Coins.user.domain.UserRepository:
    class: ../../../../../Contexts/CoinsCtx/User/infrastructure/SanityUserRepository
    arguments: [ '' ]

  Coins.user.application.UserRegister:
    class: ../../../../../Contexts/CoinsCtx/User/application/UserRegister
    arguments: [ '@Coins.user.domain.UserRepository' ]

  Coins.user.application.UserLogin:
    class: ../../../../../Contexts/CoinsCtx/User/application/UserLogin
    arguments: [ '@Coins.user.domain.UserRepository' ]

  Coins.user.application.ValidateUserService:
    class: ../../../../../Contexts/CoinsCtx/User/application/ValidateUserService
    arguments: [ '' ]

  Coins.user.application.JWTService:
    class: ../../../../../Contexts/CoinsCtx/User/application/JWTService
    arguments: [ '' ]

  Coins.user.application.AddFavoritesService:
    class: ../../../../../Contexts/CoinsCtx/User/application/AddFavoritesService
    arguments: [ '@Coins.user.domain.UserRepository' ]
