import { type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

const Table = dynamic(
  () => import("~/components/organisms/Table").then((mod) => mod.CustomTable),
  {
    ssr: false,
  }
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Intermedia Watcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table />
    </>
  );
};

export default Home;
