import type { NextPage } from "next";
import Head from "next/head";
import { LoginForm } from "~/components/organisms/LoginForm";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl font-bold text-white">Intermedia Login</h1>
      <LoginForm />
    </>
  );
};

export default Login;
