import type { NextPage } from "next";
import Head from "next/head";
import { LoginForm } from "~/components/organisms/LoginForm";
import { getCookie } from "cookies-next";
import jwtDecode from "jwt-decode";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginForm />
    </>
  );
};

export default Login;

// export function getServerSideProps({ req, res }: any) {
//   // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
//   const token = getCookie("token", { req, res }) || "";
//   const decoded = jwtDecode(token) || null;
//
//   return {
//     props: {
//       token: token,
//       user: decoded?.payload,
//     },
//   };
// }
