import { type NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import { Navbar } from "~/components/molecules/Navbar";

const Table = dynamic(
  () => import("~/components/organisms/Table").then((mod) => mod.Table),
  {
    ssr: false,
  }
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Intermedia Watcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">Intermedia Watcher</h1>
        <Table />
      </main>
    </>
  );
};

export default Home;

// const client = createClient({
//   projectId: "6fyyl8sn",
//   dataset: "production",
//   apiVersion: "2023-04-06",
//   useCdn: false,
// });

// export async function getStaticProps() {
//   const query = `*[_type == "coin"]`;
//   const coins = await client.fetch(query);
//
//   return {
//     props: {
//       coins,
//     },
//   };
// }
