services:

  Apps.coins.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.coins.controllers.CoursePutController:
    class: ../../controllers/CoinPutController
    arguments: [""]
